package Vista.Medico;
import Vista.I_Inicio;

public class IDB_Medico extends javax.swing.JFrame {

    /**
     * Creates new form IDB_Medico
     */
    public IDB_Medico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        medicoDashboard_title__label = new javax.swing.JLabel();
        crearHistoria__btn = new javax.swing.JButton();
        modificarHistoria__btn = new javax.swing.JButton();
        inicio__btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        medicoDashboard_title__label.setText("Dashboard");

        crearHistoria__btn.setText("Crear Historia");
        crearHistoria__btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearHistoria__btnActionPerformed(evt);
            }
        });

        modificarHistoria__btn.setText("Modificar Historia");
        modificarHistoria__btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarHistoria__btnActionPerformed(evt);
            }
        });

        inicio__btn.setText("Inicio");
        inicio__btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio__btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(crearHistoria__btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modificarHistoria__btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(medicoDashboard_title__label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(inicio__btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(medicoDashboard_title__label)
                .addGap(59, 59, 59)
                .addComponent(crearHistoria__btn)
                .addGap(54, 54, 54)
                .addComponent(modificarHistoria__btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(inicio__btn)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void crearHistoria__btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearHistoria__btnActionPerformed
        I_CrearHistoria crearHistoria = new I_CrearHistoria();
        crearHistoria.setVisible(true);
        IDB_Medico.this.setVisible(false);
        dispose();
    }//GEN-LAST:event_crearHistoria__btnActionPerformed

    private void modificarHistoria__btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarHistoria__btnActionPerformed
        I_ModificarHistoria modificarHistoria = new I_ModificarHistoria();
        modificarHistoria.setVisible(true);
        IDB_Medico.this.setVisible(false);
        dispose();
    }//GEN-LAST:event_modificarHistoria__btnActionPerformed

    private void inicio__btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio__btnActionPerformed
        I_Inicio inicio = new I_Inicio();
        inicio.setVisible(true);
        IDB_Medico.this.setVisible(false);
        dispose();
    }//GEN-LAST:event_inicio__btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDB_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDB_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDB_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDB_Medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDB_Medico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton crearHistoria__btn;
    private javax.swing.JButton inicio__btn;
    private javax.swing.JLabel medicoDashboard_title__label;
    private javax.swing.JButton modificarHistoria__btn;
    // End of variables declaration//GEN-END:variables
}
