/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.JuntaDirectiva;

import Vista.I_Inicio;

/**
 *
 * @author Hogar
 */
public class IDB_JuntaDirectiva extends javax.swing.JFrame {

    /**
     * Creates new form IDB_JuntaDirectiva
     */
    public IDB_JuntaDirectiva() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        juntaDashboard_title__label = new javax.swing.JLabel();
        abrirSucursal__btn = new javax.swing.JButton();
        registrarMedico__btn = new javax.swing.JButton();
        generarReporte__btn = new javax.swing.JButton();
        inicio__btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        juntaDashboard_title__label.setText("Dashboard");

        abrirSucursal__btn.setText("Abrir Sucursal");
        abrirSucursal__btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirSucursal__btnActionPerformed(evt);
            }
        });

        registrarMedico__btn.setText("Registrar Médico");
        registrarMedico__btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarMedico__btnActionPerformed(evt);
            }
        });

        generarReporte__btn.setText("Generar Reporte");
        generarReporte__btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarReporte__btnActionPerformed(evt);
            }
        });

        inicio__btn.setText("Inicio");
        inicio__btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inicio__btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(166, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(abrirSucursal__btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registrarMedico__btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generarReporte__btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(164, 164, 164))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(juntaDashboard_title__label))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(inicio__btn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(juntaDashboard_title__label)
                .addGap(59, 59, 59)
                .addComponent(abrirSucursal__btn)
                .addGap(34, 34, 34)
                .addComponent(registrarMedico__btn)
                .addGap(34, 34, 34)
                .addComponent(generarReporte__btn)
                .addGap(18, 18, 18)
                .addComponent(inicio__btn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirSucursal__btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirSucursal__btnActionPerformed
        // TODO add your handling code here:
        I_AbrirSucursal abrirSucursal = new I_AbrirSucursal();
        abrirSucursal.setVisible(true);
        IDB_JuntaDirectiva.this.setVisible(false);
        dispose();
    }//GEN-LAST:event_abrirSucursal__btnActionPerformed

    private void registrarMedico__btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarMedico__btnActionPerformed
        // TODO add your handling code here:
        I_RegistrarMedico registarMedico = new I_RegistrarMedico();
        registarMedico.setVisible(true);
        IDB_JuntaDirectiva.this.setVisible(false);
        dispose();
    }//GEN-LAST:event_registrarMedico__btnActionPerformed

    private void generarReporte__btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarReporte__btnActionPerformed
        // TODO add your handling code here:
        I_ReporteAnual reporteAnual = new I_ReporteAnual();
        reporteAnual.setVisible(true);
        IDB_JuntaDirectiva.this.setVisible(false);
        dispose();
    }//GEN-LAST:event_generarReporte__btnActionPerformed

    private void inicio__btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inicio__btnActionPerformed
        // TODO add your handling code here:
        I_Inicio inicio = new I_Inicio();
        inicio.setVisible(true);
        IDB_JuntaDirectiva.this.setVisible(false);
        dispose();
    }//GEN-LAST:event_inicio__btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IDB_JuntaDirectiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IDB_JuntaDirectiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IDB_JuntaDirectiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IDB_JuntaDirectiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IDB_JuntaDirectiva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrirSucursal__btn;
    private javax.swing.JButton generarReporte__btn;
    private javax.swing.JButton inicio__btn;
    private javax.swing.JLabel juntaDashboard_title__label;
    private javax.swing.JButton registrarMedico__btn;
    // End of variables declaration//GEN-END:variables
}
